@baseUrl = http://localhost:3000/api
@authToken = {{login.response.body.token}}
@masterToken = {{masterLogin.response.body.token}}

# ========================================
# User Profile 
# ========================================

### Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "test6@example.com",
    "password": "Password123456",
    "displayName": "Test User",
    "dateOfBirth": "2000-01-01",
    "country": "Saida"
}

### Login with registered user
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "test3@example.com",
    "password": "Password1234"
}
### Get current user profile (requires authentication)
GET {{baseUrl}}/auth/me
Authorization: Bearer {{authToken}}

### Update user profile (requires authentication)
PUT {{baseUrl}}/auth/me
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "displayName": "Updated Name",
    "password": "new updated password",
    "country": "Beirut"
}

# ========================================
# Boards
# ========================================

### Create a new board (requires authentication)
POST {{baseUrl}}/boards
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Board 5",
    "description": "A test board",
    "isPrivate": false
}
### Update a board (requires board admin)
PUT {{baseUrl}}/boards/20
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "new name",
    "description": "Updated description",
    "isPrivate": true
}
### Delete a board (requires board admin)
DELETE {{baseUrl}}/boards/11
Authorization: Bearer {{authToken}}

### Get all boards
GET {{baseUrl}}/boards
Authorization: Bearer {{authToken}}

### Join a board (requires authentication)
POST {{baseUrl}}/boards/18/join
Authorization: Bearer {{authToken}}

### Leave a board (requires authentication)
DELETE {{baseUrl}}/boards/20/join
Authorization: Bearer {{authToken}}

### Get all boards that the user has joined (requires authentication)
GET {{baseUrl}}/boards/joined
Authorization: Bearer {{authToken}}

### Add member to private board (board admin only)
POST {{baseUrl}}/boards/19/members
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "userId": 10
}

### Ban user from board (Board Admin Only)
POST {{baseUrl}}/boards/18/ban/12
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "reason": "Reason ..."
}

### Get board members information (requires board membership)
GET {{baseUrl}}/boards/19/members
Authorization: Bearer {{authToken}}

# ========================================
# Master
# ========================================

### Master user login
# @name masterLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "master@example.com",
    "password": "Master123"
}
### Get all users (requires master access)
GET {{baseUrl}}/master/users
Authorization: Bearer {{masterToken}}

### Update user profile (requires master access)
PUT {{baseUrl}}/master/users/9
Authorization: Bearer {{masterToken}}
Content-Type: application/json

{
    "userId": "9",
    "email": "email@updatedby.master",
    "role": "user",
    "displayName": "by mr master",
    "country": "Jbeil",
    "password": "masterChangedPa33",
    "dateOfBirth": "2025-05-05"
}
### Get all boards (master only)
GET {{baseUrl}}/master/boards
Authorization: Bearer {{masterToken}}

### Update board (master only)(change status to frozen to ban board)
PUT {{baseUrl}}/master/boards/20
Authorization: Bearer {{masterToken}}
Content-Type: application/json

{
    "name": "banned board",
    "isPublic": true,
    "status": "frozen",
    "adminId": 1
}

### Ban user from board (requires master access)
POST {{baseUrl}}/master/boards/13/ban/10
Authorization: Bearer {{masterToken}}
Content-Type: application/json

{
    "reason": "Violation of community guidelines"
}

### Unban user from board (requires master access)
DELETE {{baseUrl}}/master/boards/20/ban/10
Authorization: Bearer {{masterToken}}

# ========================================
# MESSAGES
# ========================================
